-keepattributes *Annotation*, InnerClasses
-dontwarn kotlinx.serialization.**
-keep,includedescriptorclasses class com.vyxel.launcher.**$$serializer { *; }
-keep class com.vyxel.launcher.core.model.** { *; }
